stages:
  - build

Win7-VS14-x64-subproject:
  stage: build
  script:
  - call %ENVFILESDIR%\Boost-1.64-vs14-x64.bat
  - call %ENVFILESDIR%\Qt-5.9-vs14.bat
  - call %ENVFILESDIR%\zeromq-4.2.1-vs14-x64.bat
  - set PATH=%PATH%;"c:\Program Files (x86)\Git\bin"
  - set BUILD_GENERATOR=Visual Studio 14 Win64
  - set CMAKE_EXTRA_ARGS="-DWITH_NO_CONSOLE=ON"
  - bash --login .gitlab-ci.sh
  tags:
  - win7
  except:
  - tags
Ubuntu-subproject:
  stage: build
  script:
  - module load Qt-5.9
  - bash .gitlab-ci.sh
  tags:
  - ubuntu
  except:
  - tags
OSX-subproject:
  stage: build
  script:
  - module load Qt-5.4
  - bash .gitlab-ci.sh
  tags:
  - osx
  except:
  - tags
